CREATE DATABASE retail_sales;
USE retail_sales;
CREATE TABLE sales (
    transaction_id INT,date DATE,
    customer_id VARCHAR(20),
    gender VARCHAR(10),
    age INT,
    product_category VARCHAR(50),
    quantity INT,
    price_per_unit DECIMAL(10,2),
    total_amount DECIMAL(10,2)
);
-- Q1 Find the total revenue generated from all transactions. 
select sum(total_amount) as total_revenue
from sales;

-- Q2 Find the total number of transactions in the sales table.
select count(transaction_id) as total_transactions
from sales;

-- Q3 Find the average amount spent per transaction.
select avg(total_amount) as avg_transaction_value
from sales;

-- Q4 Find the total number of products/items sold across all transactions.
select sum(quantity) as total_quantity_sold
from sales;

-- Q5 Find the total revenue generated by each product_category.
select product_category, sum(total_amount) as total_revenue
from sales
group by product_category;

-- Q6 Find the total revenue generated by each gender.
select gender, sum(total_amount) as total_revenue
from sales
group by gender;

-- Q7 Find the average transaction amount for each gender.
select gender, avg(total_amount) as avg_transaction
from sales
group by gender;

-- Q8 Find the total revenue generated in each year.
select year(date) as year, sum(total_amount) as total_revenue
from sales
group by year(date);

-- Q9 Find the total revenue generated in each month, showing the year and month.
select year(date) as year, month(date) as month, sum(total_amount) as total_revenue
from sales
group by year(date), month(date)
order by year(date), month(date) asc;

-- Q10 Find the product category with the highest total quantity sold.
select product_category, sum(quantity) as total_quantity
from sales
group by product_category
order by total_quantity desc;

-- Q11 Find the average price per unit for each product category.
select product_category, avg(price_per_unit) as avg_price
from sales
group by product_category;

-- Q12 Find the transaction with the highest total_amount.
select *
from sales
where total_amount = (select  max(total_amount)
from sales
)
limit 1;

-- Q13 Find the product category with the highest number of transactions.
select product_category, count(transaction_id) as transaction_count
from sales
group by product_category
order by transaction_count desc
limit 1;

-- Q14 Find the customer who generated the highest total revenue.
select customer_id, sum(total_amount) as high_spent
from sales
group by customer_id
order by high_spent desc
limit 1;

-- Q15 Find the average total_amount for each age.
select age, avg(total_amount) as avg_amount
from sales
group by age
order by age desc;


-- Q16 Find the total revenue for each combination of gender and product category.
select gender, product_category, sum(total_amount) as total_revenue
from sales
group by gender, product_category
order by total_revenue desc;

-- Q17 Find the top 3 customers who spent the most money.
select customer_id, sum(total_amount) as high_spent
from sales
group by customer_id
order by high_spent desc
limit 3;

-- Q18 Find the average transaction amount for each combination of product_category and gender.
select product_category, gender, avg(total_amount) as avg_amount
from sales
group by product_category, gender
order by avg_amount desc;

-- Q19 Find the number of transactions for each month.
select month(date) as month, count(transaction_id) as cnt_transaction
from sales
group by month(date)
order by month(date) asc, cnt_transaction desc;

-- Q20 Find the month with the highest total revenue.
select month(date), sum(total_amount) as total_revenue
from sales
group by month(date)
order by total_revenue desc
limit 1;

-- Q21 Find the product category with the highest total quantity sold.
select product_category, sum(quantity) as total_quantity
from sales
group by product_category
order by total_quantity desc
limit 1;

-- Q22 Find all transactions where total_amount is greater than the overall average transaction amount.
select transaction_id, customer_id, total_amount
from sales
where total_amount> (select avg(total_amount) as avg_amount
from sales)
order by total_amount desc;

-- Q23 Find customers who have made more than 5 transactions.
select customer_id, count(transaction_id) as cnt_transaction
from sales
group by customer_id
having count(transaction_id)>5
order by cnt_transaction desc;

-- Q24 Find the total revenue generated by each age group.
select 
case
when age between 18 and 25 then '18-25'
when age between 26 and 35 then '26-35'
when age between 36 and 45 then '36-45'
when age between 46 and 55 then '46-55'
when age between 56 and 64 then '56-64'
end as 'age_group',
sum(total_amount) as total_revenue
from sales
group by age_group
order by total_revenue desc;

-- Q25 Find customers whose total spending is greater than 2,000.

select customer_id, sum(total_amount) as total_spending
from sales
group by customer_id
having sum(total_amount)>2000
order by total_spending desc;

-- Q26 Find product categories where the average transaction amount is greater than 450.
select product_category, avg(total_amount) as avg_amount
from sales
group by product_category
having avg(total_amount)>450
order by avg_amount desc;

-- Q27 Find the genders whose total revenue is greater than the average total revenue per gender.
-- select gender, sum(total_amount) as total_revenue
-- from sales
-- where total_amount >(select avg(total_amount)
-- from sales)
-- group by gender
-- having sum(total_amount) > avg(total_amount)
-- order by total_revenue desc;

SELECT gender, SUM(total_amount) AS total_revenue
FROM sales
GROUP BY gender
HAVING SUM(total_amount) > (SELECT AVG(total_revenue)
FROM (SELECT gender, SUM(total_amount) AS total_revenue
FROM sales
GROUP BY gender) AS gender_revenue)
ORDER BY total_revenue DESC;

-- Q28 Find the product category with the highest average price_per_unit.
select product_category, avg(price_per_unit) as avg_price
from sales
group by product_category
order by avg_price desc
limit 1;

-- Q29 Find the gender with the highest total spending.
select gender, sum(total_amount) as total_spending
from sales
group by gender
order by total_spending desc
limit 1;

-- Q30 Find the product category with the highest total revenue per transaction on average.
select product_category, avg(total_amount) as avg_amount
from sales
group by product_category
order by avg_amount desc
limit 1;

-- Q31 Find the average total spending per customer for each gender.
-- select customer_id, gender, sum(total_amount) as total_spending
-- from sales
-- where total_amount 
-- group by gender
-- order by avg_customer_spending desc;

SELECT gender, AVG(customer_total) AS avg_customer_spending
FROM (SELECT customer_id, gender, SUM(total_amount) AS customer_total
FROM sales
GROUP BY customer_id, gender) AS customer_spending
GROUP BY gender
ORDER BY avg_customer_spending DESC;

-- Q32 Find the customer who has the highest average transaction amount.
select customer_id, avg(total_amount) as avg_amount
from sales
group by customer_id
order by avg_amount desc
limit 1;

-- Q33 Find the top 3 customers based on the total quantity of products they purchased.
select customer_id, sum(quantity) as total_quantity
from sales
group by customer_id
order by total_quantity desc
limit 3;

-- Q34 Find the total revenue for each product category within each age group.
select product_category, 
case
when age between 18 and 25 then '18-25'
when age between 26 and 35 then '26-35'
when age between 36 and 45 then '36-45'
when age between 46 and 55 then '46-55'
when age between 56 and 64 then '56-64'
end as 'age_group',
sum(total_amount) as total_revenue
from sales
group by age_group, product_category
order by total_revenue desc;

-- Q35 Find the customer who has the highest total spending within any single product category.
select customer_id, product_category, sum(total_amount) as total_spending
from sales
group by customer_id, product_category
order by total_spending desc
limit 1;

-- Q36 Find the date with the highest total revenue.
select date, sum(total_amount) as total_revenue
from sales
group by date
order by total_revenue desc
limit 1;

-- Q37 Find the top 3 customers who purchased products from the highest number of different product categories.
select customer_id, count(distinct product_category) as different_product_category
from sales
group by customer_id
order by different_product_category desc
limit 3;

-- Q38 Find the top 3 customers based on their average quantity purchased per transaction.
select customer_id, avg(quantity) as avg_quantity
from sales
group by customer_id
order by avg_quantity desc
limit 3;

-- Q39 Find the product category that generated the highest total revenue in each year.
WITH revenue AS (
    SELECT YEAR(date) AS year, product_category, SUM(total_amount) AS total_revenue
    FROM sales
    GROUP BY YEAR(date), product_category
),
ranked AS (
    SELECT year, product_category, total_revenue,
	ROW_NUMBER() OVER (PARTITION BY year ORDER BY total_revenue DESC) AS rn
    FROM revenue
)
SELECT year, product_category, total_revenue
FROM ranked
WHERE rn = 1;

-- Q40 Find all customers and rank them based on their total spending.
with total_spending as (
select customer_id, sum(total_amount) as total_spending
from sales
group by customer_id),
ranked as (
select customer_id, total_spending,
row_number() over (order by total_spending desc) as customer_rank
from total_spending
)
select customer_id, total_spending, customer_rank
from ranked;